name: Run Selenium Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: "23"
          distribution: "temurin"
          cache: maven
      - uses: nanasess/setup-chromedriver@v1
        with:
          chrome-version: latest  # Ensure ChromeDriver matches Chrome
      - run: mvn clean verify
