name: Run Selenium Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Set up Java
      - uses: actions/setup-java@v3
        with:
          java-version: "23"
          distribution: "temurin"
          cache: maven

      # Step 3: Set up Chrome and ChromeDriver
      - name: Set up Chrome and ChromeDriver
        uses: nanasess/setup-chromedriver@v1
        with:
          chrome-version: latest  # Use the latest stable version of Chrome

      # Step 4: Run Maven tests
      - name: Run Maven tests
        run: mvn clean verify -DtestFailureIgnore=true

      # Step 5: Save Test Results and Screenshots (optional for debugging)
      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/

      - name: Archive Screenshots
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: path/to/screenshots/
